# ECON3203 Group Project: Sensational

## Explore & Prepare data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
# load data
sample_url="https://drive.google.com/uc?export=download&id=1ekCjJOTjGD0OASErwVnwhJuPD0hFfCEF"
out_url=sample_url
db_sample = pd.read_csv(sample_url)
db_out = pd.read_csv(out_url)

In [3]:
db_sample.head()

,score_read,score_math,gender,birth,lunch,ethnicity,class_type,school,degree,ladder,experience,t_ethnicity,schooldistrict_id,school_id
0,474.0,602.0,male,1980 Q2,free,cauc,small,rural,master,level1,6.0,cauc,36.0,72.0
1,403.0,434.0,male,1980 Q3,free,afam,small,rural,bachelor,apprentice,1.0,cauc,24.0,57.0
2,455.0,520.0,male,1980 Q2,non-free,cauc,regular+aide,suburban,bachelor,level1,5.0,afam,22.0,51.0
3,405.0,454.0,female,1979 Q4,free,cauc,regular+aide,rural,bachelor,level1,11.0,cauc,4.0,6.0
4,433.0,473.0,female,1980 Q3,non-free,cauc,regular,rural,bachelor,level1,2.0,cauc,40.0,76.0

- count → number of valid (non-missing) values;
- unique → number of distinct categories (categorical data only);
- top → modal (most common) category;
- freq → how often that top category appears.

In [4]:
# Simple data stats
db_sample.describe(include="all")

,score_read,score_math,gender,birth,lunch,ethnicity,class_type,school,degree,ladder,experience,t_ethnicity,schooldistrict_id,school_id
count,4643.000000,4706.000000,5060,5055,5039,5059,5060,5060,5041,4549,5041.000000,5008,5060.000000,5060.000000
unique,NaN,NaN,2,15,2,6,3,4,4,5,NaN,2,NaN,NaN
top,NaN,NaN,male,1980 Q3,non-free,cauc,regular+aide,rural,bachelor,level1,NaN,cauc,NaN,NaN
freq,NaN,NaN,2591,1333,2578,3389,1786,2351,3306,3737,NaN,4193,NaN,NaN
mean,436.272238,485.123459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.277723,NaN,18.699209,40.042885
std,31.358938,47.674836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.854946,NaN,11.046311,22.770969
min,346.000000,288.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000
25%,414.000000,454.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,11.000000,21.000000
50%,433.000000,478.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000,NaN,15.000000,39.000000
75%,453.000000,513.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,27.000000,60.000000
max,627.000000,626.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,42.000000,80.000000

In [5]:
# Categorical vars exploration
categorical_cols = db_sample.select_dtypes(include='object').columns

for col in categorical_cols:
    print(db_sample[col].value_counts(),"\n")

gender
male      2591
female    2469
Name: count, dtype: int64

birth
1980 Q3    1333
1980 Q1    1232
1980 Q2    1222
1979 Q4     901
1979 Q3     160
1979 Q2      69
1980 Q4      53
1979 Q1      43
1978 Q4      29
1978 Q2       4
1981 Q1       2
1978 Q3       2
1981 Q4       2
1978 Q1       2
1981 Q3       1
Name: count, dtype: int64

lunch
non-free    2578
free        2461
Name: count, dtype: int64

ethnicity
cauc        3389
afam        1646
asian         11
other          6
hispanic       5
amindian       2
Name: count, dtype: int64

class_type
regular+aide    1786
regular         1761
small           1513
Name: count, dtype: int64

school
rural         2351
inner-city    1134
suburban      1123
urban          452
Name: count, dtype: int64

degree
bachelor      3306
master        1581
master+        121
specialist      33
Name: count, dtype: int64

ladder
level1        3737
apprentice     413
probation      261
level2          97
level3          41
Name: count, dtype: int64

t_ethnicity
cauc    4193
afam     815
Name: count, dtype: int64

Explore Missing data if it is randomly or not

In [6]:
# Count missing values and calculate missing rate per column
missing_counts = db_sample.isnull().sum()
missing_rate = db_sample.isnull().mean()

# Combine into a summary DataFrame
missing_summary = pd.DataFrame({
    'Missing Count': missing_counts,
    'Missing Rate (%)': (missing_rate * 100).round(2)
})
# Count rows with at least one missing value
num_missing_rows = db_sample.isnull().any(axis=1).sum()

# Display
print(f"Missing Value Summary: {num_missing_rows} ({(num_missing_rows/len(db_sample)*100).round(2)}%) unique missing rows")
missing_summary

Missing Value Summary: 903 (17.85%) unique missing rows

                   Missing Count  Missing Rate (%)
score_read                   417              8.24
score_math                   354              7.00
gender                         0              0.00
birth                          5              0.10
lunch                         21              0.42
ethnicity                      1              0.02
class_type                     0              0.00
school                         0              0.00
degree                        19              0.38
ladder                       511             10.10
experience                    19              0.38
t_ethnicity                   52              1.03
schooldistrict_id              0              0.00
school_id                      0              0.00

In [7]:
def missing_rate(df, var, group_by):
    """
    Prints missingness rate of a variable grouped by another variable.

    Parameters:
    - df: pandas DataFrame
    - var: column name to check for missing values (string)
    - group_by: column name to group by (string)
    """
    # Calculate missingness rate
    missing_rate = df[var].isna().groupby(df[group_by]).mean()

    # Filter to show only groups with missing values
    missing_groups = missing_rate[missing_rate > 0]

    # Print result
    print(f"\nMissing rate for '{var}' grouped by '{group_by}': {len(missing_groups)} missing")
    print(missing_groups.round(4))

missing_rate(db_sample, "score_read", "gender")
missing_rate(db_sample, "ladder", "school")
missing_rate(db_sample, "ladder", "school_id")
missing_rate(db_sample, "ladder", "schooldistrict_id")

Missing rate for 'score_read' grouped by 'gender': 2 missing
gender
female    0.0826
male      0.0822
Name: score_read, dtype: float64

Missing rate for 'ladder' grouped by 'school': 4 missing
school
inner-city    0.1323
rural         0.0515
suburban      0.1781
urban         0.0885
Name: ladder, dtype: float64

Missing rate for 'ladder' grouped by 'school_id': 24 missing
school_id
1.0     0.5424
4.0     0.2353
17.0    0.1875
18.0    0.2817
20.0    0.5246
25.0    0.7407
27.0    0.1707
28.0    0.2833
32.0    0.5579
33.0    0.0952
34.0    0.2321
35.0    0.3704
37.0    0.2593
42.0    0.2295
43.0    0.4746
44.0    0.4789
45.0    0.3111
47.0    0.2245
48.0    0.2317
50.0    0.2059
51.0    0.1121
58.0    0.2051
71.0    0.3333
73.0    0.1754
Name: ladder, dtype: float64

Missing rate for 'ladder' grouped by 'schooldistrict_id': 13 missing
schooldistrict_id
1.0     0.5424
4.0     0.0870
11.0    0.1544
12.0    0.1953
13.0    0.2593
18.0    0.3147
19.0    0.2245
20.0    0.2317
21.0    0.1228
22.0    0.0494
25.0    0.2051
36.0    0.1312
37.0    0.1754
Name: ladder, dtype: float64

- 19 rows of missing experience is not random, only in school_id = 48 or school_district = 20 missing 23% of this variable among their groups. Those schools are in urban (4% missing), class_type is regular_aide (1%), ethnicity is cauc (0.56%).

-> Drop 19 missing rows of ladder
- 511 rows of missing ladder potentially not random, 54% of the missing ladder is in school_id=1 or school_district=1.

-> Label the missing rows in ladder and clasified as 'Missing'

In [8]:
# Filter and display all columns for school_id = 1
school_1_data = db_sample[db_sample['school_id'] == 1]

print(school_1_data.count())

score_read           53
score_math           53
gender               59
birth                59
lunch                59
ethnicity            59
class_type           59
school               59
degree               59
ladder               27
experience           59
t_ethnicity          59
schooldistrict_id    59
school_id            59
dtype: int64

In [9]:
# Drop missing rows in experience
db_sample.dropna(subset=["experience"], inplace=True)

# Fill in missing values in ladder with new label 'Missing'
db_sample["ladder"] = db_sample["ladder"].fillna("Missing")

# Count value occurrences in the 'ladder' column
print(db_sample['ladder'].value_counts())
db_sample.describe(include='all')

ladder
level1        3737
Missing        492
apprentice     413
probation      261
level2          97
level3          41
Name: count, dtype: int64

,score_read,score_math,gender,birth,lunch,ethnicity,class_type,school,degree,ladder,experience,t_ethnicity,schooldistrict_id,school_id
count,4624.000000,4687.000000,5041,5036,5020,5040,5041,5041,5041,5041,5041.000000,5008,5041.000000,5041.000000
unique,NaN,NaN,2,15,2,6,3,4,4,6,NaN,2,NaN,NaN
top,NaN,NaN,male,1980 Q3,non-free,cauc,regular+aide,rural,bachelor,level1,NaN,cauc,NaN,NaN
freq,NaN,NaN,2583,1330,2569,3370,1767,2351,3306,3737,NaN,4193,NaN,NaN
mean,436.298443,485.183913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.277723,NaN,18.694307,40.012894
std,31.396538,47.722186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.854946,NaN,11.066824,22.808599
min,346.000000,288.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000
25%,414.000000,454.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,11.000000,21.000000
50%,433.000000,478.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000,NaN,15.000000,39.000000
75%,453.000000,513.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,27.000000,60.000000
max,627.000000,626.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,42.000000,80.000000

## Modeling

In [10]:
# Complicate name in birth , just gonna remove for now
db_sample = db_sample.drop(columns=['birth'])

In [11]:
# Drop missing values of score_read
db_read = db_sample.dropna(subset=["score_read"])
db_read.describe(include='all')

,score_read,score_math,gender,lunch,ethnicity,class_type,school,degree,ladder,experience,t_ethnicity,schooldistrict_id,school_id
count,4624.000000,4621.000000,4624,4609,4624,4624,4624,4624,4624,4624.000000,4593,4624.000000,4624.000000
unique,NaN,NaN,2,2,6,3,4,4,6,NaN,2,NaN,NaN
top,NaN,NaN,male,non-free,cauc,regular+aide,rural,bachelor,level1,NaN,cauc,NaN,NaN
freq,NaN,NaN,2370,2367,3111,1620,2201,3007,3459,NaN,3875,NaN,NaN
mean,436.298443,485.435187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.326990,NaN,18.745242,40.023356
std,31.396538,47.665392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.819284,NaN,11.146944,23.016896
min,346.000000,339.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000
25%,414.000000,454.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,11.000000,20.000000
50%,433.000000,484.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000,NaN,15.000000,39.000000
75%,453.000000,513.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,28.000000,61.000000
max,627.000000,626.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,42.000000,80.000000

In [12]:
# Make catagorical vars into dummy vars
db_read=pd.get_dummies(db_read, drop_first=True)
db_read.rename(columns={'lunch_non-free': 'lunch_nonfree'}, inplace=True)
db_read.rename(columns={'class_type_regular+aide': 'class_type_regular_aide'}, inplace=True)
db_read.rename(columns={'degree_master+': 'degree_masterplus'}, inplace=True)
db_read.describe(include="all")

,score_read,score_math,experience,schooldistrict_id,school_id,gender_male,lunch_nonfree,ethnicity_amindian,ethnicity_asian,ethnicity_cauc,...,school_urban,degree_master,degree_masterplus,degree_specialist,ladder_apprentice,ladder_level1,ladder_level2,ladder_level3,ladder_probation,t_ethnicity_cauc
count,4624.000000,4621.000000,4624.000000,4624.000000,4624.000000,4624,4624,4624,4624,4624,...,4624,4624,4624,4624,4624,4624,4624,4624,4624,4624
unique,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,NaN,NaN,NaN,NaN,NaN,True,True,False,False,True,...,False,False,False,False,False,True,False,False,False,True
freq,NaN,NaN,NaN,NaN,NaN,2370,2367,4622,4613,3111,...,4225,3149,4512,4594,4241,3459,4534,4583,4405,3875
mean,436.298443,485.435187,9.326990,18.745242,40.023356,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,31.396538,47.665392,5.819284,11.146944,23.016896,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,346.000000,339.000000,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,414.000000,454.000000,5.000000,11.000000,20.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,433.000000,484.000000,9.000000,15.000000,39.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,453.000000,513.000000,13.000000,28.000000,61.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,627.000000,626.000000,27.000000,42.000000,80.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
db_sample

# need to filter some variables.

,score_read,score_math,gender,lunch,ethnicity,class_type,school,degree,ladder,experience,t_ethnicity,schooldistrict_id,school_id
0,474.0,602.0,male,free,cauc,small,rural,master,level1,6.0,cauc,36.0,72.0
1,403.0,434.0,male,free,afam,small,rural,bachelor,apprentice,1.0,cauc,24.0,57.0
2,455.0,520.0,male,non-free,cauc,regular+aide,suburban,bachelor,level1,5.0,afam,22.0,51.0
3,405.0,454.0,female,free,cauc,regular+aide,rural,bachelor,level1,11.0,cauc,4.0,6.0
4,433.0,473.0,female,non-free,cauc,regular,rural,bachelor,level1,2.0,cauc,40.0,76.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5055,434.0,520.0,female,free,cauc,small,rural,master,level1,8.0,cauc,40.0,76.0
5056,470.0,576.0,male,non-free,cauc,small,urban,master,level1,17.0,cauc,20.0,48.0
5057,474.0,626.0,female,non-free,cauc,regular,rural,master,level1,15.0,cauc,5.0,7.0
5058,NaN,NaN,female,free,afam,small,inner-city,bachelor,level1,11.0,cauc,11.0,27.0
5059,458.0,528.0,male,non-free,cauc,regular+aide,suburban,bachelor,level1,7.0,cauc,22.0,54.0

### OLS of score_read

In [13]:
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from statsmodels.formula.api import ols

# Define X and y
X = db_read.drop(columns=['score_read', 'score_math'])
y = db_read['score_read']

formula = f'score_read ~ {" + ".join(X.columns)}'
print(formula)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit OLS model full
OLSmodel = ols(formula, data=pd.concat([X_train, y_train], axis =1)).fit()

# Predict and evaluate
y_pred = OLSmodel.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

# Print summary and MSE
print(OLSmodel.summary())
print(f"Mean Squared Error: {mse}")

score_read ~ experience + schooldistrict_id + school_id + gender_male + lunch_nonfree + ethnicity_amindian + ethnicity_asian + ethnicity_cauc + ethnicity_hispanic + ethnicity_other + class_type_regular_aide + class_type_small + school_rural + school_suburban + school_urban + degree_master + degree_masterplus + degree_specialist + ladder_apprentice + ladder_level1 + ladder_level2 + ladder_level3 + ladder_probation + t_ethnicity_cauc
                            OLS Regression Results
==============================================================================
Dep. Variable:             score_read   R-squared:                       0.116
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     20.08
Date:                Mon, 27 Oct 2025   Prob (F-statistic):           5.30e-81
Time:                        00:56:25   Log-Likelihood:                -17772.
No. Observations:                3699   AIC:                         3.559e+04
Df Residuals:                    3674   BIC:                         3.575e+04
Df Model:                          24
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                         419.6308      2.299    182.495      0.000     415.123     424.139
gender_male[T.True]                -6.5838      0.977     -6.736      0.000      -8.500      -4.667
lunch_nonfree[T.True]              14.1810      1.128     12.572      0.000      11.969      16.393
ethnicity_amindian[T.True]        -17.1594     29.725     -0.577      0.564     -75.439      41.120
ethnicity_asian[T.True]            -4.1893     10.626     -0.394      0.693     -25.024      16.645
ethnicity_cauc[T.True]              6.4983      1.682      3.864      0.000       3.201       9.796
ethnicity_hispanic[T.True]         16.5726     14.948      1.109      0.268     -12.734      45.879
ethnicity_other[T.True]             3.7597     13.386      0.281      0.779     -22.485      30.004
class_type_regular_aide[T.True]     1.1281      1.193      0.946      0.344      -1.211       3.467
class_type_small[T.True]            5.6904      1.240      4.588      0.000       3.259       8.122
school_rural[T.True]               -2.7556      2.105     -1.309      0.190      -6.882       1.371
school_suburban[T.True]             0.1490      1.887      0.079      0.937      -3.551       3.849
school_urban[T.True]                1.1982      2.434      0.492      0.623      -3.574       5.970
degree_master[T.True]              -1.3058      1.139     -1.146      0.252      -3.540       0.928
degree_masterplus[T.True]           0.3647      3.332      0.109      0.913      -6.168       6.897
degree_specialist[T.True]          -3.2727      6.078     -0.538      0.590     -15.189       8.644
ladder_apprentice[T.True]           7.1032      2.393      2.968      0.003       2.411      11.795
ladder_level1[T.True]               6.9747      1.916      3.640      0.000       3.218      10.732
ladder_level2[T.True]              21.8459      4.159      5.253      0.000      13.693      29.999
ladder_level3[T.True]              31.8104      5.519      5.764      0.000      20.990      42.631
ladder_probation[T.True]            9.0699      2.809      3.229      0.001       3.563      14.577
t_ethnicity_cauc[T.True]           -2.2227      1.572     -1.414      0.157      -5.304       0.859
experience                          0.4301      0.100      4.280      0.000       0.233       0.627
schooldistrict_id                   0.1353      0.203      0.666      0.506      -0.263       0.534
school_id                          -0.0924      0.095     -0.969      0.333      -0.280       0.095
==============================================================================
Omnibus:                      968.576   Durbin-Watson:                   1.978
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3259.654
Skew:                           1.298   Prob(JB):                         0.00
Kurtosis:                       6.796   Cond. No.                     3.15e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.15e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
Mean Squared Error: 867.9761983573015

### OLS for score_math

In [14]:
# Drop missing values of score_math
db_math = db_sample.dropna(subset=["score_math"])

# MAke dammu vars
db_math=pd.get_dummies(db_math, drop_first=True)
db_math.rename(columns={'lunch_non-free': 'lunch_nonfree'}, inplace=True)
db_math.rename(columns={'class_type_regular+aide': 'class_type_regular_aide'}, inplace=True)
db_math.rename(columns={'degree_master+': 'degree_masterplus'}, inplace=True)
db_math.describe(include="all")

,score_read,score_math,experience,schooldistrict_id,school_id,gender_male,lunch_nonfree,ethnicity_amindian,ethnicity_asian,ethnicity_cauc,...,school_urban,degree_master,degree_masterplus,degree_specialist,ladder_apprentice,ladder_level1,ladder_level2,ladder_level3,ladder_probation,t_ethnicity_cauc
count,4621.000000,4687.000000,4687.000000,4687.000000,4687.000000,4687,4687,4687,4687,4687,...,4687,4687,4687,4687,4687,4687,4687,4687,4687,4687
unique,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,NaN,NaN,NaN,NaN,NaN,True,True,False,False,True,...,False,False,False,False,False,True,False,False,False,True
freq,NaN,NaN,NaN,NaN,NaN,2402,2403,4685,4676,3144,...,4283,3202,4573,4657,4296,3489,4597,4646,4458,3924
mean,436.303614,485.183913,9.301899,18.729038,40.025603,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,31.405520,47.722186,5.849657,11.105611,22.923302,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,346.000000,288.000000,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,414.000000,454.000000,5.000000,11.000000,21.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,433.000000,478.000000,9.000000,15.000000,39.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,453.000000,513.000000,13.000000,27.000000,60.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,627.000000,626.000000,27.000000,42.000000,80.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Define X and y
X = db_math.drop(columns=['score_read', 'score_math'])
y = db_math['score_math']

formula = f'score_math ~ {" + ".join(X.columns)}'
print(formula)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit OLS model full
OLSmodel = ols(formula, data=pd.concat([X_train, y_train], axis=1)).fit()

# Predict and evaluate
y_pred = OLSmodel.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

# Print summary and MSE
print(OLSmodel.summary())
print(f"Mean Squared Error: {mse}")

score_math ~ experience + schooldistrict_id + school_id + gender_male + lunch_nonfree + ethnicity_amindian + ethnicity_asian + ethnicity_cauc + ethnicity_hispanic + ethnicity_other + class_type_regular_aide + class_type_small + school_rural + school_suburban + school_urban + degree_master + degree_masterplus + degree_specialist + ladder_apprentice + ladder_level1 + ladder_level2 + ladder_level3 + ladder_probation + t_ethnicity_cauc
                            OLS Regression Results
==============================================================================
Dep. Variable:             score_math   R-squared:                       0.098
Model:                            OLS   Adj. R-squared:                  0.093
Method:                 Least Squares   F-statistic:                     16.92
Date:                Mon, 27 Oct 2025   Prob (F-statistic):           4.31e-67
Time:                        00:56:25   Log-Likelihood:                -19642.
No. Observations:                3749   AIC:                         3.933e+04
Df Residuals:                    3724   BIC:                         3.949e+04
Df Model:                          24
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                         460.2468      3.417    134.707      0.000     453.548     466.946
gender_male[T.True]                -6.4076      1.502     -4.267      0.000      -9.352      -3.463
lunch_nonfree[T.True]              18.5773      1.750     10.615      0.000      15.146      22.008
ethnicity_amindian[T.True]        -39.6634     32.519     -1.220      0.223    -103.420      24.093
ethnicity_asian[T.True]            -8.9896     14.063     -0.639      0.523     -36.561      18.581
ethnicity_cauc[T.True]             10.1553      2.621      3.875      0.000       5.017      15.294
ethnicity_hispanic[T.True]        -11.0626     26.620     -0.416      0.678     -63.254      41.129
ethnicity_other[T.True]            26.7126     23.075      1.158      0.247     -18.529      71.954
class_type_regular_aide[T.True]     1.2379      1.825      0.678      0.498      -2.340       4.816
class_type_small[T.True]            9.3662      1.903      4.922      0.000       5.635      13.097
school_rural[T.True]               -0.8966      3.233     -0.277      0.782      -7.235       5.442
school_suburban[T.True]             4.4537      2.910      1.531      0.126      -1.251      10.159
school_urban[T.True]                1.3219      3.773      0.350      0.726      -6.076       8.720
degree_master[T.True]              -4.8990      1.767     -2.772      0.006      -8.364      -1.434
degree_masterplus[T.True]          -9.9630      4.913     -2.028      0.043     -19.596      -0.330
degree_specialist[T.True]           8.9245      9.772      0.913      0.361     -10.234      28.083
ladder_apprentice[T.True]          11.6057      3.603      3.222      0.001       4.543      18.669
ladder_level1[T.True]               8.8980      2.834      3.139      0.002       3.341      14.455
ladder_level2[T.True]              18.8957      6.142      3.077      0.002       6.854      30.937
ladder_level3[T.True]              28.9870      8.479      3.418      0.001      12.362      45.612
ladder_probation[T.True]           14.8902      4.195      3.550      0.000       6.666      23.115
t_ethnicity_cauc[T.True]           -5.0634      2.420     -2.092      0.037      -9.809      -0.318
experience                          0.6695      0.153      4.373      0.000       0.369       0.970
schooldistrict_id                   0.8984      0.313      2.866      0.004       0.284       1.513
school_id                          -0.4436      0.148     -3.007      0.003      -0.733      -0.154
==============================================================================
Omnibus:                      174.666   Durbin-Watson:                   2.040
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              200.605
Skew:                           0.534   Prob(JB):                     2.75e-44
Kurtosis:                       3.379   Cond. No.                     2.26e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.26e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
Mean Squared Error: 1968.4921063368952